name: clickControl
display:  Allows the adjustment of click controlled paramteres
description: Controls Click
execute: thread
mainfile: clickControl.py
inherits:
   - DispatchAgent

software:
   - python-netifaces
