name: iperf
magi_version: 1.7
display: iperf
description: run iperf on clients and servers
execute: thread 
mainfile: iperf_agent.py
inherits:
  - DispatchAgent
software:
  - iperf3 
variables:
  - name: flows
    help: This is a list of client to server pairs, in python dict format with 'client' and ;'server' keys. Example: "[{'client': 'foo' 'server': 'baz'}, {'client': 'bar' 'server': 'koala'}]"
    type: string
  - name: client_args
    help:
  - name: logdir
    help: Where to log iperf output.
    default: /tmp/iperf
    type: string
  - name: json
    type: boolean
    default: true
    help: If true, output JSON instead of text.
method:
  - name: start_traffic
    help: Start iperf traffic
    args:
  - name: stop_traffic
    help: Stop iperf traffic
    args:
