name: nodeStats
magi_version: 1.7
display: Node Statistics
description: An agent that collects general node information and CPU + load average statistics
execute: thread 
mainfile: nodeStats.py
software:
  - libdeterdash
inherits:
  - ReportingDispatchAgent
variables:
  - name: truncate
    help: If true, truncate Magi database records on start or restart of the agent.
    type: boolean
  - name: recordLimit
    help: Limit the number of records about the node to the number given.
    type: integer
  - name: visualize
    help: If true, make stats available to the situational awareness application.
    type: boolean
method: 
  - name: startCollection
    help: Start collecting stats about this node.
    args: { }
  - name: stopCollection
    help: Stop collecting stats about this node.
    args: { }

