name: GstreamerRTPViz
magi_version: 1.9
display: GstreamerRTPViz
description: Reads GstreamerRTP log file and reports to visulization system.
execute: thread 
mainfile: GstreamerRTPAgentViz.py
inherits:
  - ReportingDispatchAgent
software:
  - python-pycurl
  - libdeterdash
  - libffi-dev
  - flex
  - bison
  - libglib2.0-dev
  - yasm
  - libxv-dev
  - libsdl-pango-dev
  - libx264-dev
  - libmpg123-dev
  - libavcodec-dev
  - python-gi-dev
  - gstreamer_1.8_custom



