name: tcpdump
magi_version: 1.7
display: tcpdump agent
description: tcpdump
mainfile: tcpdump.py
execute: thread 
software:
    - python-netifaces
inherits:
    - DispatchAgent
varibles:
    - name: dumpfile
      help: Default dump file location. Can be overridden during the startCollection() call.
      type: str
      default: "/tmp/tcpdump.cap"
method:
    - name: startCollection
      help: Start collecting TCP dump information.
      args:
        - name: dumpfile
          help: Path to the file in which to write the tcp packets. This is optional as there is a default.
          default: "/tmp/tcpdump.cap"
        - name: expression
          type: str
          help: The expression passed to tcpdump. e.g. "dst foobar" or "src 10.0.1.1 proto udp"
        - name: tcpdump_args
          help: extra, non-expression args, to pass to the tcpdump process when starting.
          type: str
        - name: capture_address
          help: If given, capture on the interface which has this address. Overridden by "destination", if used.
          type: str
        - name: destination
          help: If given, capture on the local interface that routes to destination. Overrides capture_address. Can be specified as hostname or ip address.
          type: str
    - name: stopCollection
      help: Stop collecting TCP dump information.
      args: {}
    - name: archiveDump
      help: Write the tpcdump file to the given path/directory. The file will be uniquely named based on the host and agent name from which the file comes.
      args:
        - name: archivepath
          help: The path to the archive directory. It will be created if it does not exist. This should probably be a shared or NFS mounted directory so all files from all agents will be written to one directory.
          type: str
        - name: dumpfile
          help: The location of the tcpdump cature file to copy. Optional if defaults are used. 
          type: str
